# Generated by Django 5.2 on 2025-04-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='release_date',
            field=models.DateField(default='0001-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='synced_lyrics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
