# Generated by Django 5.2 on 2025-04-28 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_song_lyrics_song_release_date_song_synced_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ep',
            name='cover_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ep',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='library',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='libraries', to='player.song'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='single',
            name='cover_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='single',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='song',
            name='ep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='player.ep'),
        ),
        migrations.AddField(
            model_name='song',
            name='single',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='player.single'),
        ),
        migrations.AddField(
            model_name='song',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ep',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='albums',
            field=models.ManyToManyField(blank=True, related_name='libraries', to='player.album'),
        ),
        migrations.AlterField(
            model_name='library',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='libraries', to='player.artist'),
        ),
        migrations.AlterField(
            model_name='library',
            name='eps',
            field=models.ManyToManyField(blank=True, related_name='libraries', to='player.ep'),
        ),
        migrations.AlterField(
            model_name='library',
            name='playlists',
            field=models.ManyToManyField(blank=True, related_name='libraries', to='player.playlist'),
        ),
        migrations.AlterField(
            model_name='library',
            name='singles',
            field=models.ManyToManyField(blank=True, related_name='libraries', to='player.single'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='player.song'),
        ),
        migrations.AlterField(
            model_name='single',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='player.album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(max_length=500, upload_to='songs/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
