# Generated by Django 5.2 on 2025-04-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_remove_library_songs_queue_queueitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='currently_playing_order',
            field=models.IntegerField(default=0, help_text='Order of the track currently playing or last played from the queue.'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='current_track_index',
            field=models.IntegerField(default=0, help_text='Order of the next track to be played from the queue.'),
        ),
    ]
