# Generated by Django 5.2 on 2025-05-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_queue_currently_playing_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['track_number', 'title'], 'verbose_name_plural': 'Songs'},
        ),
        migrations.AddField(
            model_name='song',
            name='track_number',
            field=models.PositiveIntegerField(blank=True, help_text='Track number within the release', null=True),
        ),
    ]
